name: Android Debug Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Download Real-ESRGAN model
        if: env.HF_TOKEN != ''
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          MODEL_URL="https://huggingface.co/qualcomm/Real-ESRGAN-x4plus/resolve/main/Real-ESRGAN-x4plus.tflite"
          mkdir -p app/src/main/assets
          echo "Downloading Real-ESRGAN model..."
          curl -L -H "Authorization: Bearer $HF_TOKEN" "$MODEL_URL" -o app/src/main/assets/model.tflite
          ls -lh app/src/main/assets/model.tflite

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Sign Debug APK with generic key
        run: |
          echo "Generating generic debug keystore..."
          keytool -genkeypair -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android,O=Android,C=US"
          echo "Signing APK..."
          jarsigner -keysto
